---
title: "EDA - Template"
author: "Exploratory Data Analysis"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
    #includes:
    #    in_header: inputs_esteticos_para_relatorio/preamble.tex
  html_document:
     theme: spacelab
     toc: true
     toc_depth: 2
     toc_float: true
     smooth_scroll: false
     number_sections: true
     highlight: tango
     code_folding: hide
classoption: "aspectratio=169"
editor_options:
  chunk_output_type: console
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      message=FALSE,
                      warning = F,
                      results = 'asis',
                      fig.align='center',  out.height= '100%', 
                      fig.pos='H',
                      out.width="100%",
                      fig.margin=F)
options("kableExtra.html.bsTable" = T)
options(tinytex.verbose = TRUE)
options(knitr.kable.NA = "-")
rm(list = setdiff(objects(),c("main.directory","usuario", "params") ))

.libPaths("~/R/lib")

```

```{r}

library(ggplot2)
library(data.table)
library(pracma)
library(dplyr)
library(stats)
library(ggthemes)
library(grid)
library(gridExtra)
library(cowplot)
library(jsonlite)


theme_set(theme_pander(base_size = 10) + theme(legend.position = "bottom"))
```

```{r}
.blue   = "#1D7C96"
.mauve  = "#d46edb"
.orange = "#f27b1f"
.bistre = "#876f5c"
.gray   = "#6b8599"
.green  = "#2a9d8f"

```


```{r}

# Dados
# ......................
dt <- fread("~/experiments/sin.csv")
sweep.dt <- fread("~/experiments/sweep.csv")
sweep.savgol.dt <- fread("~/experiments/sweep_savgol.csv")



# Resultados
# .......................


coef.files <- c(
                "~/experiments/results_eiv.csv",
                "~/experiments/results_linreg_multisine.csv",
                "~/experiments/results_gradient.csv",
                #"~/experiments/results_linreg_sweep.csv",
                "~/experiments/results_linreg.csv"
                )

coef.dt <- data.table()
for (f in coef.files) {
  coef.dt <- rbind(coef.dt,
                   fread(f))
}

coef.dt[model=="sin_projection_linreg", model := "linreg_multisine"]
model.colors <- data.table(color=c(.blue, .mauve, .orange, .bistre, .green),
                           model=c("linreg", "gradient", "eiv", "linreg_sweep", "linreg_multisine"),
                           marker=c(0, 1, 2, 3, 4))
coef.dt <- coef.dt %>% merge(., model.colors, by="model")


# 
# .........................
```


```{r}


min.freq <- dt[, min(freq)]
max.freq <- dt[, max(freq)]


plot.data.freq <- function(sel.freq) {
  
  sel.dt <- dt[
             (freq == sel.freq) &
             
              
             (t > 1/sel.freq*10) &
             (t < 1/sel.freq*14)]

  g1 <- ggplot(sel.dt[axis=="x"]) +
          geom_line(aes(x=t, y=x, color=.blue)) +
          geom_line(aes(x=t, y=y, color=.orange)) +
          scale_color_identity("",
                               labels = c("x", "y"), breaks=c(.blue, .orange),
                               guide = "legend") +
          scale_y_continuous(name="Posição (m)") + 
          theme_pander(base_size = 10)
  
  g2 <- ggplot(sel.dt[axis=="x"]) +
          geom_line(aes(x=t, y=fx, color=.blue)) +
          geom_line(aes(x=t, y=fy, color=.orange)) +
          scale_color_identity("",
                               labels = c("Fx", "Fy"), breaks=c(.blue, .orange),
                               guide = "legend") +
          scale_y_continuous(name="Força (N)") + 
          theme_pander(base_size = 10)
  
  g <- plot_grid(g1, g2, ncol=1, align="v")

  return(g)
}


```

```{r}
g.data.4hz <- plot.data.freq(min.freq)
g.data.69hz <- plot.data.freq(max.freq)

```


```{r}


g_legend<-function(a.gplot){
  
    tmp <- ggplot_gtable(ggplot_build(a.gplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)
    
}

plot.coefs <- function(coefs, y.label=NULL) {
  gs <- list()
  
  if (is.null(y.label)) {
    if ("kxx" %in% coefs) {
      y.label <- "Stiffness [N/m]"
    } else if ("cxx" %in% coefs) {
      y.label <- "Damping [Ns/m]"
    }
  }
  
  for (sel.coef in coefs) {
    g <- ggplot(coef.dt) +
          #geom_hline(yintercept = groundtruth[[sel.coef]], linetype="dashed", color=.gray, alpha=0.65) +
          geom_point(data= coef.dt[!grepl("sweep", model, fixed=T)], aes_string(x="freq", y=sel.coef, color="color", shape="marker")) +
          geom_line(aes_string(x="freq", y=sel.coef, color="color", shape="marker"), alpha=0.5) +
          scale_color_identity("", labels=model.colors$model,
                               breaks=model.colors$color,
                               guide="legend") + 
      scale_shape_identity("", labels=model.colors$model,
                           breaks=model.colors$marker, guide="legend") + 
      scale_x_continuous("Frequency [Hz]") +
      scale_y_continuous(y.label) +
      ggtitle(sel.coef) + 
      theme(legend.position = "bottom")
    gs[[sel.coef]] <- g
  }
  
  
  
  mylegend<-g_legend(g)
  
  for(n in names(gs)) {
    gs[[n]] <- gs[[n]] + theme(legend.position = "none")
  }
  
  gg <- grid.arrange(arrangeGrob(grobs=gs), mylegend, heights=c(10, 1))
  return(gg)
}


g.coefs.k <- plot.coefs(c("kxx", "kxy", "kyx", "kyy"))
g.coefs.c <- plot.coefs(c("cxx", "cxy", "cyx", "cyy"))

plot(g.coefs.k)
plot(g.coefs.c)
```


```{r}

coef.long.dt <- melt(coef.dt, id.vars = c("model", "freq", "color", "marker", "savgol"))
coef.long.dt <- merge(coef.long.dt[model != "eiv"], coef.long.dt[model == "eiv", .(freq, variable, baseline_value = value)],
                      by=c('freq', 'variable'))

rmse <- function(x) {
  
  sqrt(mean(x^2))
}

error <- coef.long.dt[, .(error = rmse(value - baseline_value)), by=.(model, variable, color)]



coefs <- c("kxx", "kxy", "kyx", "kyy")

plot.errors <- function(error, coefs) {
  gs <- list()
for (coef in coefs) {
  g <- ggplot(error[variable == coef]) + geom_col(aes(x=model, y=error, fill=color)) +
  scale_fill_identity("",
                       breaks=error$color,
                       labels=error$model, guide="none")  +
  scale_y_continuous(coef) 
  
  gs[[coef]] <- g
}

  
gg <- grid.arrange(arrangeGrob(grobs=gs))


return(gg)
}

errors.k <- plot.errors(error, c("kxx", "kxy", "kyx", "kyy"))
errors.c <- plot.errors(error, c("cxx", "cxy", "cyx", "cyy"))

```


```{r}

plot.sin.data <- function(sel.dt) {
  
  scale.x <- scale_x_continuous("time [s]")
  g1 <- ggplot(sel.dt) + geom_line(aes(x=t, y=x)) +
    scale_y_continuous("Displacement, horizontal axis [m]") +
    scale.x +
                                theme(legend.position = "none") +
                  guides(color=guide_legend(nrow=2))

  g2 <- ggplot(sel.dt) + geom_line(aes(x=t, y=fx),
                                 alpha=1)  +
    scale_y_continuous("Force, horizontal axis [N]") +
    scale.x +
    theme(legend.position = "none")
  
  g3 <- ggplot(sel.dt) + geom_line(aes(x=t, y=y),
                                 alpha=1) +
    scale_y_continuous("Displacement, vertical axis [m]") +
    scale.x +
                                theme(legend.position = "none")

  g4 <- ggplot(sel.dt) + geom_line(aes(x=t, y=fy),
                                 alpha=1) +
    scale_y_continuous("Force, vertical axis [N]") +
    scale.x +
    theme(legend.position = "none")
  
  
  gs <- list(g1, g2, g3, g4)
  
  gg <- plot_grid(g1, g2, g3, g4, ncol=2, nrow=2, align="v")
  
  
  return(gg)
}

g.sin.4hz <- plot.sin.data(dt[(t <= 1/min.freq*4) & (axis == "x") & (freq == min.freq)])
plot(g.sin.4hz)

g.sin.69hz <- plot.sin.data(dt[(t <= 1/max.freq*4) & (axis == "x") & (freq == max.freq)])

```


```{r Save images}

save.at <- "~/R/images/"

save.path <- function(x) paste0(save.at, x)
ggsave(save.path(sprintf("data_experiments_%shz.png", min.freq)), g.sin.4hz)
ggsave(save.path(sprintf("data_experiments_%shz.png", max.freq)), g.sin.69hz)
ggsave(save.path("data_experiments_results_k.png"), g.coefs.k)
ggsave(save.path("data_experiments_results_c.png"), g.coefs.c)

ggsave(save.path("data_experiments_errors_k.png"), errors.k)
ggsave(save.path("data_experiments_errors_c.png"), errors.c)



ggsave(save.path("data_experiments_sweep_x.png"), g.sweep.x)
ggsave(save.path("data_experiments_sweep_y.png"), g.sweep.y)

ggsave(save.path("data_experiments_sweep_savgol_x.png"), g.sweep.savgol.x)
ggsave(save.path("data_experiments_sweep_savgol_y.png"), g.sweep.savgol.y)
ggsave(save.path("data_experiments_sweep_savgol.png"), g.sweep.savgol)
ggsave(save.path("data_experiments_sweep_savgol_dot.png"), g.sweep.savgol.dot)



```

