---
title: "EDA - Template"
author: "Exploratory Data Analysis"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
    #includes:
    #    in_header: inputs_esteticos_para_relatorio/preamble.tex
  html_document:
     theme: spacelab
     toc: true
     toc_depth: 2
     toc_float: true
     smooth_scroll: false
     number_sections: true
     highlight: tango
     code_folding: hide
classoption: "aspectratio=169"
editor_options:
  chunk_output_type: console
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      message=FALSE,
                      warning = F,
                      results = 'asis',
                      fig.align='center',  out.height= '100%', 
                      fig.pos='H',
                      out.width="100%",
                      fig.margin=F)
options("kableExtra.html.bsTable" = T)
options(tinytex.verbose = TRUE)
options(knitr.kable.NA = "-")
rm(list = setdiff(objects(),c("main.directory","usuario", "params") ))

.libPaths("~/R/lib")

```

```{r}

library(ggplot2)
library(data.table)
library(pracma)
library(dplyr)
library(stats)
library(ggthemes)
library(grid)
library(gridExtra)
library(cowplot)
library(jsonlite)


theme_set(theme_pander())
```

```{r}
.blue   = "#1D7C96"
.mauve  = "#d46edb"
.orange = "#f27b1f"
.bistre = "#876f5c"
.gray   = "#6b8599"
.green  = "#2a9d8f"

```


```{r}

# Dados
# ......................
dt <- fread("~/simulation/data/sin/excitation_sinusoidal.csv")
multisine.dt <- fread("~/simulation/data/multisin/excitation_multisine.csv")
sweep.dt <- fread("~/simulation/data/sweep/excitation_sweep.csv")
multisine.dt <- fread("~/simulation/data/multisin/excitation_multisine.csv")
sweep.savgol.dt <- fread("~/simulation/data/sweep/excitation_sweep_savgol.csv")

# Resultados
# .......................
coef.files <- c("~/simulation/data/sin/linreg.csv",
                "~/simulation/data/sin/gradient.csv",
                "~/simulation/data/sin/eiv.csv",
                "~/simulation/data/sweep/linreg_sweep.csv",
                "~/simulation/data/multisin/sin_projection_linreg.csv")

coef.dt <- data.table()
for (f in coef.files) {
  coef.dt <- rbind(coef.dt,
                   fread(f))
}
coef.dt[model=="sin_projection_linreg", model := "linreg_multisine"]
model.colors <- data.table(color=c(.blue, .mauve, .orange, .bistre, .green),
                           model=c("linreg", "gradient", "eiv", "linreg_sweep", "linreg_multisine"))
coef.dt <- coef.dt %>% merge(., model.colors, by="model")

config.json <- read_json("~/simulation/data/sin/config.json")

groundtruth <- c("kxx" = config.json$K[[1]][1],
       "kxy" = config.json$K[[1]][2],
       "kyx" = config.json$K[[2]][1],
       "kyy" = config.json$K[[2]][2],
       "cxx" = config.json$C[[1]][1],
       "cxy" = config.json$C[[1]][2],
       "cyx" = config.json$C[[2]][1],
       "cyy" = config.json$C[[2]][2])


# 
# .........................
```



```{r}




```


```{r}


sel.freq <- 4


plot.data.freq <- function(sel.freq) {
  
  sel.dt <- dt[(episode == 0) &
             (freq == sel.freq) &
             (seal == T) &
             (t > 1/sel.freq*10) &
             (t < 1/sel.freq*14)]

  g1 <- ggplot(sel.dt[axis=="x"]) +
          geom_line(aes(x=t, y=x, color=.blue)) +
          geom_line(aes(x=t, y=y, color=.orange)) +
          scale_color_identity("",
                               labels = c("x", "y"), breaks=c(.blue, .orange),
                               guide = "legend") +
          scale_y_continuous(name="Posição (m)") + 
          theme_pander()
  
  g2 <- ggplot(sel.dt[axis=="x"]) +
          geom_line(aes(x=t, y=fx, color=.blue)) +
          geom_line(aes(x=t, y=fy, color=.orange)) +
          scale_color_identity("",
                               labels = c("Fx", "Fy"), breaks=c(.blue, .orange),
                               guide = "legend") +
          scale_y_continuous(name="Força (N)") + 
          theme_pander()
  
  g <- plot_grid(g1, g2, ncol=1, align="v")

  return(g)
}


g.data.4hz <- plot.data.freq(4)
g.data.69hz <- plot.data.freq(69)

```

```{r multisine, eval=F}

 ggplot(multisine.dt[axis=="x"][1:10000]) +
          geom_line(aes(x=t, y=fx, color=.blue)) +
          geom_line(aes(x=t, y=fy, color=.orange)) +
          scale_color_identity("",
                               labels = c("Fx", "Fy"), breaks=c(.blue, .orange),
                               guide = "legend") +
          scale_y_continuous(name="Força (N)") + 
          theme_pander()

ggplot(multisine.dt[axis=="x"][1:10000]) +
          geom_line(aes(x=t, y=y, color=.blue)) +
          #geom_line(aes(x=t, y=x, color=.orange)) +
          scale_color_identity("",
                               labels = c("y", "x"), breaks=c(.blue, .orange),
                               guide = "legend") +
          scale_y_continuous(name="Pos") + 
          theme_pander()
```


```{r}


g_legend<-function(a.gplot){
  
    tmp <- ggplot_gtable(ggplot_build(a.gplot))
    leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
    legend <- tmp$grobs[[leg]]
    return(legend)
    
}

plot.coefs <- function(dt=coef.dt, coefs, zoom=F) {
  gs <- list()
  for (sel.coef in coefs) {
    g <- ggplot(dt) +
          geom_hline(yintercept = groundtruth[[sel.coef]], linetype="dashed", color=.gray, alpha=0.65) +
          geom_point(data= dt[!grepl("sweep", model, fixed=T)], aes_string(x="freq", y=sel.coef, color="color")) +
          geom_line(data= dt[grepl("sweep", model, fixed=T)], aes_string(x="freq", y=sel.coef, color="color"), alpha=0.25) +
          geom_line(data= dt[!grepl("sweep", model, fixed=T)], aes_string(x="freq", y=sel.coef, color="color"), alpha=0.5) +
          scale_color_identity("", labels=model.colors$model, breaks=model.colors$color,
                               guide="legend") + 
      ggtitle(sel.coef) + 
      theme(legend.position = "bottom")
    
    if (zoom) {
      y.max <- coef.dt[model != "linreg_sweep", max(get(sel.coef), na.rm=T)]
      y.min <- coef.dt[model != "linreg_sweep", min(get(sel.coef), na.rm=T)]
      
      g <- g + coord_cartesian(ylim=c(y.min, y.max))
      
    }
    gs[[sel.coef]] <- g
  }
  

  
  
  
  mylegend<-g_legend(g)
  
  for(n in names(gs)) {
    gs[[n]] <- gs[[n]] + theme(legend.position = "none")
  }
  
  gg <- grid.arrange(arrangeGrob(grobs=gs), mylegend, heights=c(10, 1))
  return(gg)
}


g.coefs.k <- plot.coefs(dt=coef.dt, coefs=c("kxx", "kxy", "kyx", "kyy"))
g.coefs.c <- plot.coefs(dt=coef.dt, coefs=c("cxx", "cxy", "cyx", "cyy"))

plot(g.coefs.k)
plot(g.coefs.c)

g.coefs.k.wo.sweep <- plot.coefs(dt=coef.dt,
                                 coefs=c("kxx", "kxy", "kyx", "kyy"),
                                 zoom=T)
g.coefs.c.wo.sweep <- plot.coefs(dt=coef.dt,
                                 coefs=c("cxx", "cxy", "cyx", "cyy"),
                                 zoom=T)

plot(g.coefs.k.wo.sweep)
plot(g.coefs.c.wo.sweep)


plot.coef.bar.error <- function(coef.dt, sel.coef) {

  dt <- coef.dt[, .(model, freq, color, coef=get(sel.coef))] %>% setnames(., "coef", sel.coef)

  
  dt <- melt(dt, id.vars = c("model", "freq", "color"))
  dt[, expected_value := groundtruth[[sel.coef]]]
  dt[, error := expected_value - value]
  
  sel.dt <- dt[, .(error=sqrt(mean(error^2, na.rm=T))), by=.(model, color)]
  error_adjust = sel.dt[, max(error)]/15
  ggplot(sel.dt) +
    geom_col(aes(x=model, y=error, fill=color), alpha=0.8) +
    scale_fill_identity() +
    scale_y_continuous(paste0("RMSE (", sel.coef, ")")) + 
    geom_text(aes(x=model, y=error+error_adjust, label=round(error, 1))) +
    scale_x_discrete("")
  
}


gg.error.ks <- lapply(c("kxx", "kyx", "kxy", "kyy"),
              function(x) plot.coef.bar.error(coef.dt, sel.coef=x))
gg.error.cs <- lapply(c("cxx", "cyx", "cxy", "cyy"),
              function(x) plot.coef.bar.error(coef.dt, sel.coef=x))

gg.error.ks <- plot_grid(plotlist=gg.error.ks)
gg.error.cs <- plot_grid(plotlist=gg.error.cs)
```


```{r}

library(RColorBrewer)
n <- 60
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

sel.dt <- sweep.dt[(axis == "x")]#[3950:20000]


plot.sweep.data <- function(sel.dt) {
  
  g1 <- ggplot(sel.dt) + geom_line(aes(x=t, y=x, group= episode , color = as.factor(episode)),
                                 alpha=0.5) + scale_color_manual("Episódio", values=col_vector) +
                  guides(color=guide_legend(nrow=2))

  g2 <- ggplot(sel.dt) + geom_line(aes(x=t, y=fx, group= episode , color = as.factor(episode)),
                                 alpha=0.5) + scale_color_manual("Episódio", values=col_vector) + theme(legend.position = "none")
  
  g3 <- ggplot(sel.dt) + geom_line(aes(x=t, y=y, group= episode , color = as.factor(episode)),
                                 alpha=0.5) + scale_color_manual("Episódio", values=col_vector) +
                                theme(legend.position = "none")

  g4 <- ggplot(sel.dt) + geom_line(aes(x=t, y=fy, group= episode , color = as.factor(episode)),
                                 alpha=0.5) + scale_color_manual("Episódio", values=col_vector) + theme(legend.position = "none")
  
  
  mylegend<-g_legend(g1)
  
  g1 <- g1 + theme(legend.position = "none")
  gs <- list(g1, g2, g3, g4)
  
  gg <- grid.arrange(arrangeGrob(grobs=gs, ncol=2, nrow=2, layout_matrix=rbind(c(1,3), c(2,4))), mylegend, heights=c(10, 1))
  
  
  return(gg)
}


g.sweep.x <- plot.sweep.data(sweep.dt[(axis=="x")])
g.sweep.y <- plot.sweep.data(sweep.dt[(axis=="y")])


g.sweep.x <- plot.sweep.data(sweep.dt[(axis=="x") & (seal == F)])
g.sweep.x <- plot.sweep.data(sweep.dt[(axis=="x") & (seal == T)])


g.sweep.savgol.x <- plot.sweep.data(sweep.savgol.dt[(axis=="x")])
g.sweep.savgol.y <- plot.sweep.data(sweep.savgol.dt[(axis=="y")])

g.sweep.savgol.x <- plot.sweep.data(sweep.savgol.dt[(axis=="x") & (seal == F)])
g.sweep.savgol.y <- plot.sweep.data(sweep.savgol.dt[(axis=="y") & (seal == T)])

g.sweep.x
```



```{r Save images}

save.at <- "~/R/images/"

save.path <- function(x) paste0(save.at, x)
ggsave(save.path("data_simulation_4hz.png"), g.data.4hz)
ggsave(save.path("data_simulation_69hz.png"), g.data.69hz)
ggsave(save.path("data_simulation_results_k.png"), g.coefs.k)
ggsave(save.path("data_simulation_results_c.png"), g.coefs.c)
ggsave(save.path("data_simulation_results_k_wo_sweep.png"), g.coefs.k.wo.sweep)
ggsave(save.path("data_simulation_results_c_wo_sweep.png"), g.coefs.c.wo.sweep)
ggsave(save.path("data_simulation_results_error_ks.png"), gg.error.ks)
ggsave(save.path("data_simulation_results_error_cs.png"), gg.error.cs)

```

